### ISSUE TITLE
Feature Request/Suggestion: Automated Penalties

### ISSUE THREAD

**Issue by KrisV147** [LennysLounge/ACC-Race-Control#12]
Seeing as this is already tracking and flagging cars that breach an imposed speed limit durinng a VSC/FCY, wouldnt it be possible to issue a server penalty command automatically for those that breach the speed limit for X amount of seconds total?

**Comment by LennysLounge** [comment]
No.
There is no interface for issuing server commands throught the broadcasting interface.

**Comment by schmedia-dev** [comment]
Just for understanding or maybe as a suggestion
There are programs that can adjust the settings for the teammate's pit stop in endurance races.
Unfortunately, I don't know how this is technically solved, since the programs are all chargeable and the source code is not public.
Perhaps a chat message could also be entered in this way
![pitstop_compressed](https://user-images.githubusercontent.com/46371122/189598247-008ea841-00d7-46d2-af0a-40829af6f0a8.gif)
