### ISSUE TITLE
Bug: The 'Command' field is not automatically filled with latest template 1.3.0

### ISSUE THREAD

**Issue by schmetti-dev** [LennysLounge/ACC-Race-Control#13]
The 'Ruling' and 'Car' fields are filled, but 'Command' remains empty

![image](https://user-images.githubusercontent.com/46371122/189546536-fa7048b5-902a-45b1-9647-1a8cf6bbdc45.png)

**Comment by LennysLounge** [comment]
![image](https://user-images.githubusercontent.com/25527438/189552888-3a0ed597-9b4a-42e1-95c4-1ea23e08e244.png)
I cannot replicate this with a fresh copy of the template.

In your screenshot the "Replay time" column should be filled out but it is not. Maybe that is related to your problem.
The cells C4 and K4 should have an array formula to fill in the whole column. Check those.

Otherwise i will have to look at the file directly.
