### ISSUE TITLE
Clear entry list before repopulating?

### ISSUE THREAD

**Issue by NoComment1105** [LennysLounge/ACC-Race-Control#25]
Hi there, this is more a request/question rather than a true issue, I was going to make a PR but the current behaviour is intentional so I thought I'd come here first.

So for our leagues we do live stewarding through your tool, alongside running a license point system for penalties handed out, which we total up and assign to the drive number in the entry list automatically. It's more of a "we're lazy" thing, but if the entry list isn't cleared prior to connecting the spreadsheet and no one remembers, we get an issue of the points being assigned to the wrong driver and then tracked in our points tracker incorrectly.

It's not too big of a deal but just a quick request, no worries if you'd rather keep the current behaviour. Thanks :)

**Comment by LennysLounge** [comment]
I dont think thats a great idea because it will become very difficult to know what kind of data is correct and what is wrong and can be cleared.

For example somebody might connect to the sheet at the end of the race but at that point, 5 people have already left the race.
These people will then be delete from the entry list.
The effort to get the lost data back is then greater than dealing with the fact that you might have to manually delete something yourself.

In general the google sheet should only be seen as a database and not an application in itself. RaceControl only ever writes to the database. What you end up doing with that data is up to you. From my experience, trying to make google sheets do to much ends up beeing very birttle and hard to work with.

I dont know exactly what your setup is but the way i always did it was that i had an empty sheet as the template and would copy that sheet for every race. That way we always started with a fresh empty sheet and didnt have to delete anything.

**Comment by NoComment1105** [comment]
I completely understand and putting it that way about connecting later is something i'd not considered, I'll close this now 👍🏼
